### ISSUE TITLE
Typo in the about us page

### ISSUE THREAD

**Issue by Giorgi-Sekhniashvili** [Supernova-PulsarAIGeorgia/Jipitauri-chat-bot#1]
ამ ხაზზე ტაიპოა, "ჩართვას" უნდა იყოს და არა "ჩრთვას"
https://github.com/supernova-ge/Jipitauri/blob/3d889404ef66e33f9cce8b358cb4907f204d7803/about/src/App.js#L27

**Comment by zaal** [comment]
მადლობა გიორგი, გავასწორებთ
