### ISSUE TITLE
duplicated feedback

### ISSUE THREAD

**Issue by enelene** [Supernova-PulsarAIGeorgia/Jipitauri-chat-bot#11]
ერთიდაიგივე პასუხის რამდენჯერმე შეფასება შეუძლია, ისე რომ feedback ყოველ ჯერზე ახლიდან იგზავნება.
მაგალითად : რომ დააწვე ლაიქს, შემდეგ წაშალო და თავიდან შეაფასო, არ წაშლის ძველ feedbackს და ახალსაც დაამატებს.

**Comment by LukaDarsalia** [comment]
გასწორდა შემდეგ commit-ში: ca190ce941970cf5be26ea3ab9987a577f2c2f98

**Comment by zaal** [comment]
🙌
