### ISSUE TITLE
DATABASE URL

### ISSUE THREAD

**Issue by AIContributor** [Supernova-PulsarAIGeorgia/Jipitauri-chat-bot#2]
What is it database url?

**Comment by sodesu1** [comment]
It's `mongodb connection string`,  as a data source is set to `mongodb` within a  `schema.prisma` file.

But, we'll make sure to say that  explicitly in the readme as well. 

Thank you.

@iraklinish

**Comment by AIContributor** [comment]
Can we write mysql settings instead of mogodb?

**Comment by sodesu1** [comment]
Yes, you can.

As long as your `schema.prisma` is configured to `mysql` as well.

**Comment by AIContributor** [comment]
I created the tables of manual and the site turned on but no response to the answer to the Chatbot

**Comment by AIContributor** [comment]
I did everything according to the instructions, it was installed without errors, but it does not answer the question

**Comment by sodesu1** [comment]
Seems that something is misconfigured, but you don't get any error messages. 

I'll make sure to expose silent errors. :pray: 

@iraklinish

**Comment by AIContributor** [comment]
Does AI only know information until 2021?
