### ISSUE TITLE
Mask personalised data (name, surname, phone, id, etc)

### ISSUE THREAD

**Issue by admin-pulsar** [Supernova-PulsarAIGeorgia/Jipitauri-chat-bot#4]

**Comment by admin-pulsar** [comment]
----

**Comment by anajobava** [comment]
We use regular expressions to identify personal information in a dataset. We search for patterns that match typical formats for ID numbers and phone numbers in Georgia, and then mask them. This change will help us comply with data privacy regulations and best practices, and it will be useful for our future data processing steps.

Masked Data: https://drive.google.com/file/d/1K_C2diXsp3iB_2R4tIE95m2-PwhMvaME/view?usp=sharing
