### ISSUE TITLE
Clustering and topic analyses using embeddings

### ISSUE THREAD

**Issue by admin-pulsar** [Supernova-PulsarAIGeorgia/Jipitauri-chat-bot#8]
Use Transformers

**Comment by admin-pulsar** [comment]
@NMikaa მოკლე აღწერა დაურთე

**Comment by NMikaa** [comment]
კლასტერიზაციისას K-means-ით გამოვყავით 5 კლასტერი სადაც კარგად იყო განაწილებული ყველა დისლაიქის თემატიკა. ტოპიკ ანალიზისი გავაკეთეთ BERTsenclu-თი მას შემდეგ რაც LDA-მ არ მოგვცა შედეგი, რის შედეგადაც გამოვყავით 5 ტოპიკი რომელიც ემთხვეოდა კლასტერების თემატიკას აზრობრივად, თუმცა უფრო ზუსტი და კონკრეტული იყო.
